# Generated by Django 5.1.7 on 2025-09-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OLSS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticeboard',
            old_name='notice',
            new_name='notice_subject',
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notices_files/'),
        ),
    ]
