# Generated by Django 5.1.7 on 2025-10-04 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OLSS', '0003_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student_name',
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='OLSS.student'),
            preserve_default=False,
        ),
    ]
