# Generated by Django 5.1.7 on 2025-10-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OLSS', '0004_remove_payment_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('phonepe', 'PhonePe')], max_length=20),
        ),
    ]
